//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public Distribution()
        {
            this.Arrive = new HashSet<Arrive>();
            this.Hygiene = new HashSet<Hygiene>();
            this.Register = new HashSet<Register>();
            this.Repairs = new HashSet<Repairs>();
        }
    
        public int DistributionID { get; set; }
        public string DistributionNum { get; set; }
        public string DistributionName { get; set; }
        public string DistributionImg { get; set; }
        public string DistributionAcademic { get; set; }
        public string DistributionGoods { get; set; }
        public System.DateTime DistributionTime { get; set; }
    
        public virtual ICollection<Arrive> Arrive { get; set; }
        public virtual ICollection<Hygiene> Hygiene { get; set; }
        public virtual ICollection<Register> Register { get; set; }
        public virtual ICollection<Repairs> Repairs { get; set; }
    }
}
