//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DormitoryDBEntitie : DbContext
    {
        public DormitoryDBEntitie()
            : base("name=DormitoryDBEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Arrive> Arrive { get; set; }
        public DbSet<Distribution> Distribution { get; set; }
        public DbSet<HostelNotice> HostelNotice { get; set; }
        public DbSet<Hygiene> Hygiene { get; set; }
        public DbSet<Register> Register { get; set; }
        public DbSet<Repairs> Repairs { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
