//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RegisterID { get; set; }
        public string RegisterName { get; set; }
        public string RegisterGoods { get; set; }
        public int DistributionID { get; set; }
        public string RegisterType { get; set; }
        public System.DateTime RegisterTime { get; set; }
    
        public virtual Distribution Distribution { get; set; }
    }
}
